# -----------------------------------------
# Allgemeine App-Metadaten
# -----------------------------------------

hidden: false
icon: "🛰️"
stage: "stable"

# -----------------------------------------
# Upstream-Informationen
# -----------------------------------------

upstream_version: "1.18.1"
upstream_repo: "github.com/fosrl/newt"
upstream_commit: "7856d5f4c12e2afcadad182cca357bbbb6c80dc3"
autoupdater: true

# -----------------------------------------
# Build / Lint / QA
# -----------------------------------------

build: ""
lint: ""
yaml_lint: ""
code_quality: ""

# -----------------------------------------
# Image
# -----------------------------------------

image_size: "36 MB"

# -----------------------------------------
# Custom Badges
# -----------------------------------------

custom_shield: ""
custom_flag: ""

updated: "2026-10-02"
source: "github.com/fosrl/newt"
