# -----------------------------------------
# Allgemeine App-Metadaten
# -----------------------------------------

hidden: false
icon: "🛰️"
stage: "stable"

# -----------------------------------------
# Upstream-Informationen
# -----------------------------------------

upstream_version: "1.16.0"
upstream_repo: "github.com/fosrl/newt"
upstream_commit: "0e415f0a01223dd53d19185083048e0017c755b3"
autoupdater: true

# -----------------------------------------
# Build / Lint / QA
# -----------------------------------------

build: ""
lint: ""
yaml_lint: ""
code_quality: ""

# -----------------------------------------
# Image
# -----------------------------------------

image_size: "34 MB"

# -----------------------------------------
# Custom Badges
# -----------------------------------------

custom_shield: ""
custom_flag: ""

updated: "2026-08-19"
source: "github.com/fosrl/newt"
