hidden: false
icon: "🔗"
stage: "experimental"
version_strategy: "portainer_selector"
upstream_version: "2.44.0"
upstream_repo: "docker.io/portainer/agent"
upstream_commit: "sha256:d57c3d57774d524f9738d07e743a2e8d3d65ea74bc2a39bc17b20ac0fd768e75"
lts_tracking_tag: "alpine"
lts_version: "2.39.5"
lts_commit: "sha256:ec9223788fe62872bc78d23ad4f4a5558ff560500d2602f378ea191f560f491e"
sts_tracking_tag: "alpine-sts"
sts_version: "2.44.0"
sts_commit: "sha256:d57c3d57774d524f9738d07e743a2e8d3d65ea74bc2a39bc17b20ac0fd768e75"
autoupdater: true
build: ""
lint: ""
yaml_lint: ""
code_quality: ""
image_size: "69 MB"
custom_shield: ""
custom_flag: ""
updated: "2026-07-31"
source: "docker.io/portainer/agent"
