hidden: false
icon: 🏠
stage: experimental
version_strategy: upstream_revision
upstream_strategy: openccu_overlay
upstream_version: 3.89.11.20260921-ed3aedd
upstream_repo: https://github.com/OpenCCU/OpenCCU
upstream_commit: sha256:2968b92ff46664f9b07924825fbc72696266141d911dba3fba48c64813e5d2f5
autoupdater: true
updated: '2026-09-21'
source: github.com/OpenCCU/OpenCCU
