hidden: false
icon: 🏠
stage: experimental
version_strategy: upstream_revision
upstream_strategy: openccu_overlay
upstream_version: 3.89.11.20260928-7e1cfb8
upstream_repo: https://github.com/OpenCCU/OpenCCU
upstream_commit: sha256:dc85c070728d17d613bf5aa37bf307f9e73814f36fc11f08800cc02c090e870b
autoupdater: true
updated: '2026-09-28'
source: github.com/OpenCCU/OpenCCU
