hidden: false
icon: "🐳"
stage: "stable"
version_strategy: "upstream_revision"
upstream_version: "2.45.0"
upstream_repo: "docker.io/portainer/portainer-ce"
upstream_tracking_tag: "alpine-sts"
upstream_commit: "sha256:e6b0225f4bbc989e398c85062f7426f8cf4b61f8aca6f40bf44789d1dada1949"
autoupdater: true
build: ""
lint: ""
yaml_lint: ""
code_quality: ""
image_size: "68 MB"
custom_shield: ""
custom_flag: ""
updated: "2026-08-27"
source: "docker.io/portainer/portainer-ce"
