hidden: false
icon: "🛟"
stage: "experimental"

version_strategy: "upstream_revision"
upstream_version: "1.0.47"
upstream_repo: "github.com/Finsys/dockhand"
upstream_commit: "2a9299f932271fb6c0e2bccb0e64b096da463731"
changelog_url: "https://github.com/Finsys/dockhand/releases"
autoupdater: true

build: ""
lint: ""
yaml_lint: ""
code_quality: ""
image_size: "182 MB"
custom_shield: ""
custom_flag: ""

updated: "2026-09-12"
source: "github.com/Finsys/dockhand"
