hidden: false
icon: "🛟"
stage: "experimental"

version_strategy: "upstream_revision"
upstream_version: "1.0.51"
upstream_repo: "github.com/Finsys/dockhand"
upstream_commit: "9280f13c42adbdfb04395221930f3d7c589d98a2"
changelog_url: "https://github.com/Finsys/dockhand/releases"
autoupdater: true

build: ""
lint: ""
yaml_lint: ""
code_quality: ""
image_size: "180 MB"
custom_shield: ""
custom_flag: ""

updated: "2026-10-03"
source: "github.com/Finsys/dockhand"
