name: "Dockhand"
version: "1.0.44.3"
slug: "dockhand"
description: "Modern Docker and Compose management with Home Assistant Ingress."
stage: experimental
url: "https://dockhand.pro/manual/"
arch:
  - aarch64
  - amd64
image: "ghcr.io/sandmaennchen5/ha-repo-dockhand"
init: false
startup: services
docker_api: true
ingress: true
ingress_port: 1337
ingress_stream: true
panel_title: "Dockhand"
panel_icon: "mdi:docker"
ports:
  3000/tcp: null
ports_description:
  3000/tcp: "Direct Web UI (optional assignment)"
environment:
  DATA_DIR: "/data/dockhand"
  PUID: "0"
  PGID: "0"
options:
  storage_location: data
  share_storage_directory: dockhand-config
  remember_ingress_users: false
schema:
  storage_location: list(data|config|share)
  share_storage_directory: str
  remember_ingress_users: bool
map:
  - type: addon_config
    read_only: false
  - type: share
    read_only: false
timeout: 120
