hidden: false
icon: "⚓"
stage: "experimental"

version_strategy: "upstream_revision"
upstream_version: "1.6.1"
upstream_repo: "docker.io/codeswhat/drydock"
changelog_url: "https://github.com/CodeSWhat/drydock/blob/main/CHANGELOG.md"
autoupdater: true

build: ""
lint: ""
yaml_lint: ""
code_quality: ""
image_size: "150 MB"
custom_shield: ""
custom_flag: ""

updated: "2026-10-02"
source: "docker.io/codeswhat/drydock"

upstream_commit: "sha256:0c522e2a76cd46125478ac48f97ac4baba92b1f906f8dd91f8c9df8258bd1f8d"
