name: "Drydock"
version: "1.6.0.6"
slug: "drydock"
description: "Container update monitoring and automation with Home Assistant Ingress."
stage: experimental
url: "https://getdrydock.com/docs/"
arch:
  - aarch64
  - amd64
image: "ghcr.io/sandmaennchen5/ha-repo-drydock"
init: false
startup: services
docker_api: true
ingress: true
ingress_port: 1337
ingress_stream: true
panel_title: "Drydock"
panel_icon: "mdi:docker"
ports:
  3000/tcp: null
ports_description:
  3000/tcp: "Direct Web UI (optional assignment)"
environment:
  DD_STORE_PATH: "/data/drydock"
  DD_ANONYMOUS_AUTH_CONFIRM: "true"
  DD_SERVER_TRUSTPROXY: "1"
options:
  storage_location: data
  share_storage_directory: drydock-config
  remember_ingress_users: false
  auth_username: admin
  auth_password_hash: ""
  environment: []
schema:
  storage_location: list(data|config|share)
  share_storage_directory: str
  remember_ingress_users: bool
  auth_username: str
  auth_password_hash: password?
  environment:
    - name: match(^DD_[A-Z0-9_]+$)
      value: password
map:
  - type: addon_config
    read_only: false
  - type: share
    read_only: false
timeout: 120
