hidden: false
icon: "📊"
stage: "stable"

version_strategy: "checkmk_numeric_revision"
upstream_strategy: "github_release_branch"
upstream_version: "2.5.0p12"
upstream_repo: "github.com/Checkmk/checkmk"
upstream_commit: "888be9b83fef64cb54c5c8b2b808f37880059b5e"
autoupdater: true

build: ""
lint: ""
yaml_lint: ""
code_quality: ""
image_size: "12 MB"
custom_shield: ""
custom_flag: ""

updated: "2026-08-19"
source: "github.com/Checkmk/checkmk"
