hidden: false
icon: "📊"
stage: "stable"

version_strategy: "checkmk_numeric_revision"
upstream_strategy: "github_release_branch"
upstream_version: "2.5.0p11"
upstream_repo: "github.com/Checkmk/checkmk"
upstream_commit: "666e2404c3f03e211d5619bcca7437a20758f77c"
autoupdater: true

build: ""
lint: ""
yaml_lint: ""
code_quality: ""
image_size: "12 MB"
custom_shield: ""
custom_flag: ""

updated: "2026-08-05"
source: "github.com/Checkmk/checkmk"
