hidden: false
icon: "📊"
stage: "stable"

version_strategy: "checkmk_numeric_revision"
upstream_strategy: "github_release_branch"
upstream_version: "2.5.0p13"
upstream_repo: "github.com/Checkmk/checkmk"
upstream_commit: "7fa33e0dec6de73d1e361607884483e010a64664"
autoupdater: true

build: ""
lint: ""
yaml_lint: ""
code_quality: ""
image_size: "12 MB"
custom_shield: ""
custom_flag: ""

updated: "2026-09-03"
source: "github.com/Checkmk/checkmk"
