hidden: false
icon: "🦎"
stage: "stable"

version_strategy: "upstream_revision"
upstream_version: "0.17.0"
upstream_repo: "github.com/fosrl/cli"
upstream_commit: "213e6ff72e96c92e2fc20a913faee2c69c56425d"
autoupdater: true

build: ""
lint: ""
yaml_lint: ""
code_quality: ""
image_size: "24 MB"
custom_shield: ""
custom_flag: ""

updated: "2026-09-15"
source: "github.com/fosrl/cli"
