hidden: false
icon: "🦎"
stage: "stable"

version_strategy: "upstream_revision"
upstream_version: "0.15.1"
upstream_repo: "github.com/fosrl/cli"
upstream_commit: "fa90273f53fe77d1cbd950cb0bcba69dd4318faf"
autoupdater: true

build: ""
lint: ""
yaml_lint: ""
code_quality: ""
image_size: "23 MB"
custom_shield: ""
custom_flag: ""

updated: "2026-08-03"
source: "github.com/fosrl/cli"
