hidden: false
icon: "🦎"
stage: "stable"

version_strategy: "upstream_revision"
upstream_version: "0.16.0"
upstream_repo: "github.com/fosrl/cli"
upstream_commit: "dd61170ef18ee8b76286f18416ce6124a86e4098"
autoupdater: true

build: ""
lint: ""
yaml_lint: ""
code_quality: ""
image_size: "23 MB"
custom_shield: ""
custom_flag: ""

updated: "2026-08-21"
source: "github.com/fosrl/cli"
