name: "Pangolin CLI Client"
version: "0.15.0.1"
slug: "pangolin_cli"
description: "Official Pangolin CLI and WireGuard VPN client for Linux."
url: "https://github.com/fosrl/cli"
arch:
  - aarch64
  - amd64
image: "ghcr.io/sandmaennchen5/ha-repo-pangolin-cli"
init: false
host_network: true
privileged:
  - NET_ADMIN
devices:
  - /dev/net/tun
ports:
  2112/tcp: null
  8097/tcp: null
ports_description:
  2112/tcp: "Optional admin and Prometheus metrics endpoint"
  8097/tcp: "Internal health endpoint"
options:
  endpoint: "https://app.pangolin.net"
  client_id: ""
  client_secret: ""
  extras:
    log_level: "info"
    additional_args: ""
schema:
  endpoint: url
  client_id: str
  client_secret: password
  extras:
    log_level: list(trace|debug|info|warn|error)
    additional_args: str?
