hidden: false
icon: "🏠"
stage: "stable"

upstream_version: "13.5.1"
upstream_repo: "ghcr.io/athombv/homey-shs"
upstream_commit: "sha256:e52125f36392e237a98d837307b14017ea0d46070d1019dd559405ce0626afe3"
changelog_url: "https://homey.app/en-us/wiki/homey-shs-changelog/"
autoupdater: true

build: ""
lint: ""
yaml_lint: ""
code_quality: ""

image_size: "283 MB"

custom_shield: ""
custom_flag: ""

updated: "2026-09-29"
source: "ghcr.io/athombv/homey-shs"
