hidden: false
icon: "🏠"
stage: "stable"

upstream_version: "13.4.0"
upstream_repo: "ghcr.io/athombv/homey-shs"
upstream_commit: "sha256:97b00d6a074f8abc5d14a457f32e1c7a2b0bcbadfd56999932292efbe071abb9"
changelog_url: "https://homey.app/en-us/wiki/homey-shs-changelog/"
autoupdater: true

build: ""
lint: ""
yaml_lint: ""
code_quality: ""

image_size: "263 MB"

custom_shield: ""
custom_flag: ""

updated: "2026-07-28"
source: "ghcr.io/athombv/homey-shs"
