ARG UPSTREAM_VERSION=0.3.1
FROM ghcr.io/openccu/openccu-hapdrap:0.3.1@sha256:d433ff395bed9a64075c8d341fb9196dc3fc1b312c2e7cf79e79ef63a18b0f1c
LABEL org.opencontainers.image.source="https://github.com/sandmaennchen5/ha-repo"
