hidden: false
icon: "🔗"
stage: "stable"
version_strategy: "upstream_revision"
upstream_version: "2.39.5"
upstream_repo: "docker.io/portainer/agent"
upstream_tracking_tag: "alpine"
upstream_commit: "sha256:ec9223788fe62872bc78d23ad4f4a5558ff560500d2602f378ea191f560f491e"
autoupdater: true
build: ""
lint: ""
yaml_lint: ""
code_quality: ""
image_size: "37 MB"
custom_shield: ""
custom_flag: ""
updated: "2026-07-13"
source: "docker.io/portainer/agent"
