hidden: false
icon: "🔗"
stage: "stable"
version_strategy: "upstream_revision"
upstream_version: "2.39.6"
upstream_repo: "docker.io/portainer/agent"
upstream_tracking_tag: "alpine"
upstream_commit: "sha256:6d2fd88d1cf0284f61971854e9a65e5eeaaf48456a0b8a903a1e64842073dcfc"
autoupdater: true
build: ""
lint: ""
yaml_lint: ""
code_quality: ""
image_size: "37 MB"
custom_shield: ""
custom_flag: ""
updated: "2026-08-12"
source: "docker.io/portainer/agent"
