hidden: false
icon: "🔗"
stage: "deprecated"
version_strategy: "upstream_revision"
upstream_version: "2.45.2"
upstream_repo: "docker.io/portainer/agent"
upstream_tracking_tag: "alpine"
upstream_commit: "sha256:d4f03ec3ae2a8630394bb41df09788af3228ceb891f15b89ba6205bca07ada19"
autoupdater: true
build: ""
lint: ""
yaml_lint: ""
code_quality: ""
image_size: "42 MB"
custom_shield: ""
custom_flag: ""
updated: "2026-10-08"
source: "docker.io/portainer/agent"
