hidden: false
icon: "🍃"
stage: "stable"

version_strategy: "upstream_revision"
upstream_version: "1.9.0"
upstream_repo: "github.com/fosrl/olm"
upstream_commit: "8c1db4bada7e7425a2500ea5d76df8b85f407a91"
autoupdater: true

build: ""
lint: ""
yaml_lint: ""
code_quality: ""
image_size: "27 MB"
custom_shield: ""
custom_flag: ""

updated: "2026-08-19"
source: "github.com/fosrl/olm"
