hidden: false
icon: "🍃"
stage: "stable"

version_strategy: "upstream_revision"
upstream_version: "1.10.1"
upstream_repo: "github.com/fosrl/olm"
upstream_commit: "4901fde4b1850b56026b9740f34032dab37e7794"
autoupdater: true

build: ""
lint: ""
yaml_lint: ""
code_quality: ""
image_size: "28 MB"
custom_shield: ""
custom_flag: ""

updated: "2026-10-02"
source: "github.com/fosrl/olm"
