hidden: false
icon: "🐳"
stage: "deprecated"
version_strategy: "upstream_revision"
upstream_version: "2.45.2"
upstream_repo: "docker.io/portainer/portainer-ce"
upstream_tracking_tag: "alpine"
upstream_commit: "sha256:37aa2620d882794ed3e425b386db750f07500add53aa10adc741218b1e8d5782"
autoupdater: true
build: ""
lint: ""
yaml_lint: ""
code_quality: ""
image_size: "68 MB"
custom_shield: ""
custom_flag: ""
updated: "2026-10-08"
source: "docker.io/portainer/portainer-ce"
