hidden: false
icon: "🐳"
stage: "stable"
version_strategy: "upstream_revision"
upstream_version: "2.45.1"
upstream_repo: "docker.io/portainer/portainer-ce"
upstream_tracking_tag: "alpine"
upstream_commit: "sha256:4d9a99f4495c005388842b94d72377d5239eac8686543428c3ff7c9b6c0882bb"
autoupdater: true
build: ""
lint: ""
yaml_lint: ""
code_quality: ""
image_size: "68 MB"
custom_shield: ""
custom_flag: ""
updated: "2026-09-17"
source: "docker.io/portainer/portainer-ce"
