hidden: false
icon: "🐳"
stage: "stable"
version_strategy: "upstream_revision"
upstream_version: "2.39.6"
upstream_repo: "docker.io/portainer/portainer-ce"
upstream_tracking_tag: "alpine"
upstream_commit: "sha256:f35a74e590973d9c77fa2c4930c64c1a05626eedf64462b3d2eebef5a7c710e3"
autoupdater: true
build: ""
lint: ""
yaml_lint: ""
code_quality: ""
image_size: "62 MB"
custom_shield: ""
custom_flag: ""
updated: "2026-08-12"
source: "docker.io/portainer/portainer-ce"
