hidden: false
icon: "💼"
stage: "stable"
version_strategy: "upstream_revision"
upstream_version: "2.45.0"
upstream_repo: "docker.io/portainer/portainer-ee"
upstream_tracking_tag: "alpine"
upstream_commit: "sha256:379f8ca470e9d442f4742f33a50449638810c82e572b670354db5dbef32ed090"
autoupdater: true
build: ""
lint: ""
yaml_lint: ""
code_quality: ""
image_size: "87 MB"
custom_shield: ""
custom_flag: ""
updated: "2026-08-27"
source: "docker.io/portainer/portainer-ee"
