hidden: false
icon: "💼"
stage: "deprecated"
version_strategy: "upstream_revision"
upstream_version: "2.45.2"
upstream_repo: "docker.io/portainer/portainer-ee"
upstream_tracking_tag: "alpine"
upstream_commit: "sha256:859c869c9b1b38ef460970f178534c053cc9c5b064099504ba672338a3372bfb"
autoupdater: true
build: ""
lint: ""
yaml_lint: ""
code_quality: ""
image_size: "87 MB"
custom_shield: ""
custom_flag: ""
updated: "2026-10-08"
source: "docker.io/portainer/portainer-ee"
